name: Test

on:
  push:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: xcode-27

    steps:
      - uses: actions/checkout@v5

      - name: Build environment
        run: |
          xcodebuild -version
          xcodebuild -showsdks | grep macosx || true

      - name: Test
        run: |
          xcodebuild -project "System Spinner.xcodeproj" \
                     -scheme "System Spinner" \
                     -configuration Debug \
                     -derivedDataPath build-tests \
                     CODE_SIGNING_ALLOWED=NO \
                     test
